### PR TITLE
V1.2: Establish priority level restrictions

### LINKED ISSUE #31: As a user, I want to have administrator priviledges
so that I can use superuser commands and manage employees.

### LINKED ISSUE #38: As a elevated user, I can change the priority levels of employees
so that they have the correct level of access.

### LINKED ISSUE #40: As an elevated user, I can add/delete employees from the database
so that the company's manpower list is updated.

### PR DESCRIPTION
**Pull request by jinyao-lee**
###  [BUG FIXES]
- Fixed a bug whereby user tries to log in again when the application already has a logged in session. User must now log out before one is able to login.
- Fixed a bug whereby users are unable to login from a filtered AddressBook

### [ADD IMPLEMENTATION]
- Added priorityLevel field
- Added PriorityLevel.class and PriorityLevelEnum.class
- Added methods to get the Person details from the current logged in session's NRIC.
- Added methods to check if the logged in session meets the required priority levels to perform certain operations.
- Implemented setPriorityLevel command.
   > Requires admin priority level to set the priority of anyone other than yourself.

### [EDIT EXISTING FEATURES]
- addCommand modified to take in priorityLevel parameters.
   > If priorityLevel field omitted, lowest priorityLevel will be set by default.
- editCommand modified for priorityLevel.
   > Note: User is unable to modify NRIC, password and priorityLevel.
- addCommand, deleteCommand now requires priority level of minimum, an aministrator, to perform the operation.
- deleteCommand now stops admins from deleting themselves

### [TO-DO]
- [Medium Priority] Restrict edit function to user's own data fields.
- [Medium Priority] Implement change password.

This resolves #31 
This resolves #38 
This resolves #40

### CODE REVIEW

**Comment by Woonhian** [comment]
Good implementation on the priority level restrictions. PR approved.

**Review by Woonhian — APPROVED** [review]
Good implementation on the priority level restrictions. PR approved.

**Comment by jylee-git** [comment]
Fulfilled #31

**Comment by jylee-git** [comment]
Closed #31 

Reason: User story fulfilled

**Pull request merged**
